<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body{font-family:Arial,sans-serif;font-size:13px;color:#333;margin:0;padding:20px;}
  .header{background:#2CADA6;color:#fff;padding:20px;margin-bottom:20px;border-radius:8px;}
  .header h1{margin:0;font-size:24px;font-weight:900;}
  .header p{margin:4px 0;font-size:12px;opacity:0.85;}
  .logo{font-size:28px;font-weight:900;}
  .logo span{color:#F5A623;}
  .invoice-info{display:flex;justify-content:space-between;margin-bottom:20px;}
  .info-box{background:#F8F9FA;padding:14px;border-radius:6px;flex:1;margin:0 5px;}
  .info-box h3{margin:0 0 8px;font-size:12px;color:#999;text-transform:uppercase;letter-spacing:1px;}
  .info-box p{margin:3px 0;font-size:13px;font-weight:600;}
  table{width:100%;border-collapse:collapse;margin-bottom:20px;}
  th{background:#2CADA6;color:#fff;padding:10px 12px;text-align:left;font-size:12px;}
  td{padding:10px 12px;border-bottom:1px solid #EEE;font-size:13px;}
  tr:nth-child(even){background:#F9F9F9;}
  .total-row{background:#2CADA6!important;color:#fff;font-weight:700;}
  .total-row td{border-bottom:none;}
  .footer{text-align:center;color:#999;font-size:11px;margin-top:30px;padding-top:15px;border-top:1px solid #EEE;}
  .status-paid{background:#D1FAE5;color:#059669;padding:4px 12px;border-radius:20px;font-weight:700;font-size:12px;}
  .status-unpaid{background:#FEF3C7;color:#D97706;padding:4px 12px;border-radius:20px;font-weight:700;font-size:12px;}
  .amount{font-size:32px;font-weight:900;color:#2CADA6;}
</style>
</head>
<body>
<div class="header">
  <div style="display:flex;justify-content:space-between;align-items:center;">
    <div>
      <div class="logo">6G<span>STATS</span></div>
      <p>6G Premium Telecom NOC Platform</p>
      <p>6g-premium-telecom.com</p>
    </div>
    <div style="text-align:right;">
      <div style="font-size:20px;font-weight:700;">INVOICE</div>
      <div style="font-size:14px;opacity:0.85;">{{ $invoice->invoice_number }}</div>
      <div style="margin-top:8px;">
        <span class="{{ $invoice->status=='paid' ? 'status-paid' : 'status-unpaid' }}">
          {{ strtoupper($invoice->status ?? 'UNPAID') }}
        </span>
      </div>
    </div>
  </div>
</div>

<div class="invoice-info">
  <div class="info-box">
    <h3>Invoice Details</h3>
    <p>Number: {{ $invoice->invoice_number }}</p>
    <p>Date: {{ date('d M Y', strtotime($invoice->created_at)) }}</p>
    <p>Due Date: {{ $invoice->due_date ? date('d M Y', strtotime($invoice->due_date)) : 'Upon Receipt' }}</p>
    <p>Period: {{ date('d M Y', strtotime($invoice->period_start)) }} - {{ date('d M Y', strtotime($invoice->period_end)) }}</p>
  </div>
  <div class="info-box">
    <h3>Supplier</h3>
    <p>{{ $invoice->supplier_name ?? '6G Premium Telecom' }}</p>
    <p>Type: {{ ucfirst($invoice->invoice_type ?? 'weekly') }}</p>
    <p>Currency: {{ $invoice->currency }}</p>
  </div>
  <div class="info-box" style="text-align:center;">
    <h3>Total Amount</h3>
    <div class="amount">{{ $invoice->currency=='USD'?'$':'€' }}{{ number_format($invoice->total_amount, 4) }}</div>
  </div>
</div>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Calls</th>
      <th>Minutes</th>
      <th>Amount</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Voice Termination Services<br><small style="color:#999;">Period: {{ $invoice->period_start }} to {{ $invoice->period_end }}</small></td>
      <td>{{ number_format($invoice->total_calls) }}</td>
      <td>{{ number_format($invoice->total_minutes, 2) }}</td>
      <td style="font-weight:700;color:#2CADA6;">{{ $invoice->currency=='USD'?'$':'€' }}{{ number_format($invoice->total_amount, 4) }}</td>
    </tr>
    <tr class="total-row">
      <td colspan="3" style="text-align:right;font-size:14px;">TOTAL DUE</td>
      <td style="font-size:16px;">{{ $invoice->currency=='USD'?'$':'€' }}{{ number_format($invoice->total_amount, 4) }}</td>
    </tr>
  </tbody>
</table>

@if($invoice->notes)
<div style="background:#F8F9FA;padding:14px;border-radius:6px;margin-bottom:20px;">
  <strong>Notes:</strong> {{ $invoice->notes }}
</div>
@endif

<div class="footer">
  <p>6G Premium Telecom | 6g-premium-telecom.com | superadmin@6gpremium.com</p>
  <p>This invoice was auto-generated by 6GSTATS NOC Platform</p>
</div>
</body>
</html>
