<?php

namespace App\Services;

use Illuminate\Support\Facades\Crypt;

/**
 * Pure config-text generator for the Asterisk Configuration module.
 *
 * No filesystem/process access happens here — everything is built from
 * plain arrays/collections passed in and returned as strings, so it can be
 * unit tested in isolation and reused by both Preview (read-only) and
 * Apply (which additionally writes the result to disk via
 * AsteriskConfigManager).
 *
 * Mirrors the proven structure/skip/dedupe logic already used in
 * asterisk/bin/pjsip_generate.php, extended with:
 *  - a shared endpoint template so per-supplier blocks stay tiny
 *    (instead of each supplier repeating the full endpoint config), while
 *    still giving every supplier its OWN endpoint+identify so channel-name
 *    based supplier attribution in asterisk/agi-bin/save_cdr.php keeps working
 *  - optional userpass auth sections for suppliers with auth_type
 *    'userpass'/'both'
 *  - the DID/prefix -> IVR dialplan routing and IVR context stanzas
 */
class AsteriskConfigGenerator
{
    // Intentionally the SAME markers asterisk/bin/pjsip_generate.php already
    // writes into the live pjsip.conf, so this module recognizes and
    // replaces that existing managed block instead of duplicating it —
    // this module supersedes running that script by hand.
    public const PJSIP_BEGIN = '; === BEGIN MANAGED TRUNKS - generated, do not edit ===';
    public const PJSIP_END = '; === END MANAGED TRUNKS ===';

    public const DIALPLAN_BEGIN = '; === BEGIN MANAGED DIALPLAN - generated by Asterisk Configuration module, do not edit ===';
    public const DIALPLAN_END = '; === END MANAGED DIALPLAN ===';

    private const INSTALLED_CODECS = ['ulaw', 'alaw', 'g722', 'gsm', 'slin', 'g726', 'speex', 'opus'];

    /**
     * @param  iterable  $trunks  rows from the `trunks` table (stdClass or array)
     * @return array{text:string,names:string[],skipped:string[],warnings:string[]}
     */
    public function pjsipManagedBlock(iterable $trunks, string $inboundContext, string $defaultCodecs = 'ulaw,alaw'): array
    {
        $codecs = $this->cleanCodecs($defaultCodecs);
        $out = [self::PJSIP_BEGIN, '', '[supplier-template](!)', 'type=endpoint', "context={$inboundContext}", 'disallow=all'];
        foreach ($codecs as $c) {
            $out[] = "allow={$c}";
        }
        $out = array_merge($out, [
            'direct_media=no',
            'rtp_symmetric=yes',
            'force_rport=yes',
            'rewrite_contact=yes',
            'device_state_busy_at=0',
            '',
        ]);

        $names = [];
        $skipped = [];
        $warnings = [];
        $identifyCount = 0;

        foreach ($trunks as $t) {
            $t = (object) $t;
            if (empty($t->is_active)) {
                continue;
            }

            $label = $t->nickname ?: $t->name ?: ('supplier-'.$t->id);
            $ips = array_values(array_filter(
                array_map('trim', explode(',', (string) $t->host)),
                fn ($ip) => filter_var($ip, FILTER_VALIDATE_IP)
            ));
            if (!$ips) {
                $skipped[] = "{$label} (host \"{$t->host}\" has no valid IP)";
                continue;
            }

            $name = $t->pjsip_name ?: strtoupper(preg_replace('/[^A-Za-z0-9]+/', '-', $label));
            if (in_array($name, $names, true)) {
                $skipped[] = "{$label} (duplicate pjsip name {$name})";
                continue;
            }
            $names[] = $name;

            $port = $t->port ?: 5060;
            $trunkCodecs = $this->cleanCodecs($t->codecs ?? '') ?: $codecs;
            $authType = in_array($t->auth_type ?? 'ip', ['ip', 'userpass', 'both'], true) ? $t->auth_type : 'ip';

            $out[] = "; ── {$label} ──";
            $out[] = "[{$name}](supplier-template)";
            if ($trunkCodecs !== $codecs) {
                // supplier overrides the default codec list
                $out[] = 'disallow=all';
                foreach ($trunkCodecs as $c) {
                    $out[] = "allow={$c}";
                }
            }
            $out[] = "aors={$name}-aor";
            $useAuth = in_array($authType, ['userpass', 'both'], true) && !empty($t->sip_username) && !empty($t->sip_password);
            if ($useAuth) {
                $out[] = "auth={$name}-auth";
            }
            $out[] = '';

            $out[] = "[{$name}-aor]";
            $out[] = 'type=aor';
            $out[] = 'max_contacts=100';
            $out[] = 'qualify_frequency='.(int) ($t->qualify ?? 60);
            foreach ($ips as $ip) {
                $out[] = "contact=sip:{$ip}:{$port}";
            }
            $out[] = '';

            // Identify (IP auth) — skipped entirely for a pure userpass-only supplier
            if ($authType !== 'userpass') {
                $out[] = "[{$name}-identify]";
                $out[] = 'type=identify';
                $out[] = "endpoint={$name}";
                foreach ($ips as $ip) {
                    $out[] = "match={$ip}";
                }
                $out[] = '';
                $identifyCount++;
            }

            if ($useAuth) {
                $password = $t->sip_password;
                try {
                    $password = Crypt::decryptString($t->sip_password);
                } catch (\Throwable $e) {
                    $warnings[] = "{$label}: stored SIP password could not be decrypted, userpass auth skipped";
                    $useAuth = false;
                }
                if ($useAuth) {
                    $out[] = "[{$name}-auth]";
                    $out[] = 'type=auth';
                    $out[] = 'auth_type=userpass';
                    $out[] = 'username='.($t->sip_username);
                    $out[] = 'password='.$password;
                    $out[] = '';
                }
            }
        }

        $out[] = self::PJSIP_END;

        return [
            'text' => implode("\n", $out)."\n",
            'names' => $names,
            'skipped' => $skipped,
            'warnings' => $warnings,
            'identify_count' => $identifyCount,
        ];
    }

    /**
     * @param  iterable  $routePrefixes  rows from `route_prefixes`
     * @param  iterable  $ivrs  rows from `ivrs`
     * @return array{text:string,routes:array,errors:string[],warnings:string[]}
     */
    public function dialplanManagedBlock(iterable $routePrefixes, iterable $ivrs, string $inboundContext = 'from-suppliers'): array
    {
        $validation = $this->validatePrefixes($routePrefixes);

        $activeIvrNames = [];
        foreach ($ivrs as $ivr) {
            $ivr = (object) $ivr;
            if (!empty($ivr->is_active)) {
                $activeIvrNames[$ivr->name] = true;
            }
        }
        foreach ($validation['active'] as $row) {
            if (!isset($activeIvrNames[$row->ivr_context])) {
                $validation['warnings'][] = "Route \"{$row->prefix}\" (#{$row->id}) references IVR context \"{$row->ivr_context}\" which doesn't match any active IVR — this route will Goto a context that doesn't exist";
            }
        }

        $out = [self::DIALPLAN_BEGIN, ''];

        $out[] = "[{$inboundContext}]";
        $out[] = '';
        $out[] = 'exten => _X.,1,NoOp(6G PREMIUM TELECOM INBOUND)';
        $out[] = ' same => n,NoOp(Caller=${CALLERID(num)})';
        $out[] = ' same => n,NoOp(DID=${EXTEN})';
        $out[] = ' same => n,Goto(number-routing,${EXTEN},1)';
        $out[] = '';

        $out[] = '[number-routing]';
        $out[] = '';
        foreach ($validation['active'] as $row) {
            $pattern = $this->toDialplanPattern($row->prefix);
            $label = $row->country_name ?: $row->country_code ?: 'Route';
            $out[] = "exten => {$pattern},1,NoOp({$label} -> {$row->ivr_context})";
            $out[] = " same => n,Goto({$row->ivr_context},s,1)";
        }
        $out[] = '';
        $out[] = '; Unknown/unconfigured DID — never enters an IVR';
        $out[] = 'exten => _X.,1,NoOp(UNKNOWN DID ${EXTEN})';
        $out[] = ' same => n,Hangup()';
        $out[] = '';

        foreach ($ivrs as $ivr) {
            $ivr = (object) $ivr;
            if (empty($ivr->is_active)) {
                continue;
            }
            $out[] = "[{$ivr->name}]";
            $out[] = '';
            $out[] = 'exten => s,1,Answer()';
            $out[] = " same => n,Playback({$ivr->audio_file})";
            $out[] = ' same => n,WaitExten(10)';
            $out[] = '';
        }

        $out[] = self::DIALPLAN_END;

        return [
            'text' => implode("\n", $out)."\n",
            'routes' => $validation['active'],
            'errors' => $validation['errors'],
            'warnings' => $validation['warnings'],
        ];
    }

    public function rtpConf(int $start, int $end): string
    {
        return implode("\n", [
            '[general]',
            "rtpstart={$start}",
            "rtpend={$end}",
            '',
        ]);
    }

    /**
     * Blocking errors: exact-duplicate active prefixes (ambiguous — Asterisk
     * cannot have two identical extension patterns in the same context).
     * Warnings: one active prefix is a strict textual prefix of another,
     * which is legal (Asterisk picks the most specific match) but worth a
     * human glance before Apply.
     */
    public function validatePrefixes(iterable $routePrefixes): array
    {
        $active = [];
        foreach ($routePrefixes as $row) {
            $row = (object) $row;
            if (!empty($row->is_active)) {
                $active[] = $row;
            }
        }
        usort($active, fn ($a, $b) => ($a->priority ?? 1) <=> ($b->priority ?? 1));

        $errors = [];
        $warnings = [];
        $seen = [];
        foreach ($active as $row) {
            $key = (string) $row->prefix;
            if (isset($seen[$key])) {
                $errors[] = "Duplicate active prefix \"{$key}\" (rows #{$seen[$key]} and #{$row->id}) — ambiguous routing";
            }
            $seen[$key] = $row->id;
        }
        foreach ($active as $a) {
            foreach ($active as $b) {
                if ($a->id === $b->id) {
                    continue;
                }
                if (strlen($a->prefix) < strlen($b->prefix) && str_starts_with((string) $b->prefix, (string) $a->prefix)) {
                    $warnings[] = "Prefix \"{$a->prefix}\" (#{$a->id}) overlaps with more specific \"{$b->prefix}\" (#{$b->id})";
                }
            }
        }

        return ['active' => $active, 'errors' => $errors, 'warnings' => $warnings];
    }

    public function validateRtp(int $start, int $end): array
    {
        $errors = [];
        if ($start < 1 || $start > 65535) {
            $errors[] = 'RTP start port must be between 1 and 65535';
        }
        if ($end < 1 || $end > 65535) {
            $errors[] = 'RTP end port must be between 1 and 65535';
        }
        if ($start >= $end) {
            $errors[] = 'RTP start port must be less than RTP end port';
        }

        return $errors;
    }

    /**
     * A prefix that already contains Asterisk pattern syntax (X/Z/N/.) is
     * used verbatim; a plain digit string is treated as "starts with these
     * digits" via the standard `_<digits>.` convention.
     */
    private function toDialplanPattern(string $prefix): string
    {
        $prefix = trim($prefix);
        if ($prefix === '') {
            return '_X.';
        }
        if (preg_match('/[XZN.\[\]]/', $prefix)) {
            return str_starts_with($prefix, '_') ? $prefix : "_{$prefix}";
        }

        return "_{$prefix}.";
    }

    private function cleanCodecs(string $csv): array
    {
        $codecs = array_values(array_unique(array_filter(
            array_map('trim', explode(',', $csv)),
            fn ($c) => in_array($c, self::INSTALLED_CODECS, true)
        )));

        return $codecs ?: ['ulaw', 'alaw'];
    }
}
