<?php

namespace App\Services;

use Illuminate\Support\Facades\Crypt;

/**
 * Pure config-text generator for the Asterisk Configuration module.
 *
 * No filesystem/process access happens here — everything is built from
 * plain arrays/collections passed in and returned as strings, so it can be
 * unit tested in isolation and reused by both Preview (read-only) and
 * Apply (which additionally writes the result to disk via
 * AsteriskConfigManager).
 *
 * Mirrors the proven structure/skip/dedupe logic already used in
 * asterisk/bin/pjsip_generate.php, extended with:
 *  - a shared endpoint template so per-supplier blocks stay tiny
 *    (instead of each supplier repeating the full endpoint config), while
 *    still giving every supplier its OWN endpoint+identify so channel-name
 *    based supplier attribution in asterisk/agi-bin/save_cdr.php keeps working
 *  - optional userpass auth sections for suppliers with auth_type
 *    'userpass'/'both'
 *  - the DID/prefix -> IVR dialplan routing and IVR context stanzas
 */
class AsteriskConfigGenerator
{
    // Intentionally the SAME markers asterisk/bin/pjsip_generate.php already
    // writes into the live pjsip.conf, so this module recognizes and
    // replaces that existing managed block instead of duplicating it —
    // this module supersedes running that script by hand.
    public const PJSIP_BEGIN = '; === BEGIN MANAGED TRUNKS - generated, do not edit ===';
    public const PJSIP_END = '; === END MANAGED TRUNKS ===';

    public const DIALPLAN_BEGIN = '; === BEGIN MANAGED DIALPLAN - generated by Asterisk Configuration module, do not edit ===';
    public const DIALPLAN_END = '; === END MANAGED DIALPLAN ===';

    // Two inbound models coexist on purpose:
    //  - LEGACY_CONTEXT ('from-carrier'): hand-written in extensions.conf,
    //    dynamic per-DID lookup via did_router.php, looped Playback. Existing
    //    working suppliers keep it via trunks.dialplan_context.
    //  - NORMAL_CONTEXT ('from-suppliers'): generated here, fully static
    //    (from-suppliers -> number-routing -> IVR), no DB/HTTP in the call path.
    // Each endpoint's context is always written explicitly from
    // trunks.dialplan_context so a context never changes silently.
    public const LEGACY_CONTEXT = 'from-carrier';
    public const NORMAL_CONTEXT = 'from-suppliers';

    // Known-good production routes that Apply must never rewrite. Their
    // pjsip sections are re-emitted verbatim from the live pjsip.conf.
    public const PROTECTED_ROUTES = ['PURPLE' => 'from-carrier-purple'];
    public const PROTECTED_MESSAGE = 'Purple protected route detected. Manual migration required. No automatic change applied.';

    // Hand-written contexts the generated block must never redefine
    // (Asterisk silently merges same-named contexts).
    public const RESERVED_CONTEXTS = ['from-carrier', 'from-carrier-purple', 'block-unauthorized', 'default', 'general'];

    // Fail-safe per-supplier limits for the generated path when a trunk has none.
    /** The existing default/fallback IVR; a route on it plays a random IVR from the pool instead (see defaultIvrPoolLines). */
    public const DEFAULT_IVR = 'custom/6g-premium-telecom';
    public const DEFAULT_MAX_CHANNELS = 30;
    public const DEFAULT_MAX_DURATION = 1800;

    // g729 deliberately absent: this Asterisk has format_g729 (file format) but no
    // codec_g729 translator, so an endpoint that negotiated it could not play IVR audio.
    private const INSTALLED_CODECS = ['ulaw', 'alaw', 'g722', 'gsm', 'slin', 'g726', 'speex', 'opus'];

    /**
     * @param  iterable  $trunks  rows from the `trunks` table (stdClass or array)
     * @param  string  $inboundContext  context used for trunks with an empty dialplan_context
     * @param  string|null  $liveManagedPjsip  the CURRENT managed block of the live pjsip.conf;
     *                                          required to preserve protected routes verbatim
     * @return array{text:string,names:string[],skipped:string[],warnings:string[],errors:string[],endpoints:array,limits:array,identify_count:int}
     */
    public function pjsipManagedBlock(iterable $trunks, string $inboundContext, string $defaultCodecs = 'ulaw,alaw', ?string $liveManagedPjsip = null): array
    {
        $codecs = $this->cleanCodecs($defaultCodecs);
        $live = $liveManagedPjsip !== null ? $this->parseSections($liveManagedPjsip) : [];
        $out = [self::PJSIP_BEGIN, '', '[supplier-template](!)', 'type=endpoint', "context={$inboundContext}", 'disallow=all'];
        foreach ($codecs as $c) {
            $out[] = "allow={$c}";
        }
        $out = array_merge($out, [
            'direct_media=no',
            'trust_id_inbound=yes',
            'rtp_symmetric=yes',
            'force_rport=yes',
            'rewrite_contact=yes',
            'device_state_busy_at=0',
            '',
        ]);

        $names = [];
        $skipped = [];
        $warnings = [];
        $errors = [];
        $endpoints = [];
        $limits = [];
        $identifyCount = 0;

        foreach ($trunks as $t) {
            $t = (object) $t;
            if (empty($t->is_active)) {
                continue;
            }

            $label = $t->nickname ?: $t->name ?: ('supplier-'.$t->id);
            $name = $t->pjsip_name ?: strtoupper(preg_replace('/[^A-Za-z0-9]+/', '-', $label));
            if (in_array($name, $names, true)) {
                $skipped[] = "{$label} (duplicate pjsip name {$name})";
                $warnings[] = "{$label}: duplicate PJSIP name {$name} — skipped";
                continue;
            }

            // The name becomes a dialplan extension in [supplier-limits], so a
            // leading "_" (pattern) or odd characters would misroute limits.
            if (!preg_match('/^[A-Za-z0-9][A-Za-z0-9_-]*$/', $name)) {
                $skipped[] = "{$label} (invalid PJSIP name \"{$name}\")";
                $errors[] = "{$label}: invalid PJSIP name \"{$name}\" (letters, digits, - and _ only; must not start with _)";
                continue;
            }

            // Protected route: never regenerated, only preserved from live.
            if (isset(self::PROTECTED_ROUTES[$name])) {
                $names[] = $name;
                $this->emitProtected($name, $t, $live, $out, $errors, $warnings, $endpoints, $identifyCount);
                continue;
            }

            $ips = array_values(array_filter(
                array_map('trim', explode(',', (string) $t->host)),
                fn ($ip) => filter_var($ip, FILTER_VALIDATE_IP)
            ));
            if (!$ips) {
                $skipped[] = "{$label} (host \"{$t->host}\" has no valid IP)";
                $warnings[] = "{$label}: invalid IP in host \"{$t->host}\" — skipped";
                continue;
            }

            $context = trim((string) ($t->dialplan_context ?? '')) ?: $inboundContext;
            if (!preg_match('#^[A-Za-z0-9_\-/]+$#', $context)) {
                $skipped[] = "{$label} (invalid dialplan_context \"{$context}\")";
                $errors[] = "{$label}: invalid inbound context \"{$context}\"";
                continue;
            }
            if (in_array($context, array_values(self::PROTECTED_ROUTES), true)) {
                $errors[] = "{$label}: context \"{$context}\" is reserved for a protected route";
                continue;
            }

            $port = $t->port ?: 5060;
            $rawCodecs = array_values(array_filter(array_map('trim', explode(',', (string) ($t->codecs ?? '')))));
            $badCodecs = array_values(array_diff($rawCodecs, self::INSTALLED_CODECS));
            if ($badCodecs) {
                $warnings[] = "{$label}: invalid/unsupported codec(s) ignored: ".implode(', ', $badCodecs);
            }
            $trunkCodecs = $rawCodecs ? $this->cleanCodecs(implode(',', $rawCodecs)) : $codecs;
            $authType = in_array($t->auth_type ?? 'ip', ['ip', 'userpass', 'both'], true) ? $t->auth_type : 'ip';

            // Decrypt BEFORE emitting anything so a bad credential can never
            // leave an endpoint pointing at a missing auth section.
            $password = null;
            if ($authType !== 'ip') {
                if (!empty($t->sip_username) && !empty($t->sip_password)) {
                    try {
                        $password = Crypt::decryptString($t->sip_password);
                    } catch (\Throwable $e) {
                        $password = null;
                    }
                }
                if ($password === null) {
                    $warnings[] = "{$label}: invalid SIP authentication (auth_type={$authType} but username/password missing or undecryptable)";
                    if ($authType === 'userpass') {
                        // No identify + no auth would leave an unauthenticated endpoint.
                        $skipped[] = "{$label} (userpass auth without usable credentials)";
                        continue;
                    }
                }
            }
            $useAuth = $password !== null;

            $names[] = $name;
            $out[] = "; ── {$label} ──";
            $out[] = "[{$name}](supplier-template)";
            $out[] = "context={$context}";
            if ($trunkCodecs !== $codecs) {
                // supplier overrides the default codec list
                $out[] = 'disallow=all';
                foreach ($trunkCodecs as $c) {
                    $out[] = "allow={$c}";
                }
            }
            $out[] = "aors={$name}-aor";
            if ($useAuth) {
                $out[] = "auth={$name}-auth";
            }
            $out[] = '';

            $out[] = "[{$name}-aor]";
            $out[] = 'type=aor';
            $out[] = 'max_contacts=100';
            $out[] = 'qualify_frequency='.(int) ($t->qualify ?? 60);
            foreach ($ips as $ip) {
                $out[] = "contact=sip:{$ip}:{$port}";
            }
            $out[] = '';

            // Identify (IP auth) — skipped entirely for a pure userpass-only supplier
            if ($authType !== 'userpass') {
                $out[] = "[{$name}-identify]";
                $out[] = 'type=identify';
                $out[] = "endpoint={$name}";
                foreach ($ips as $ip) {
                    $out[] = "match={$ip}";
                }
                $out[] = '';
                $identifyCount++;
            }

            if ($useAuth) {
                $out[] = "[{$name}-auth]";
                $out[] = 'type=auth';
                $out[] = 'auth_type=userpass';
                $out[] = 'username='.($t->sip_username);
                $out[] = 'password='.$password;
                $out[] = '';
            }

            $liveContext = isset($live[$name]) ? $this->sectionValue($live[$name], 'context') : null;
            if ($liveContext !== null && $liveContext !== $context) {
                $warnings[] = "Context mismatch: {$name} is currently \"{$liveContext}\" in live pjsip.conf and would become \"{$context}\"";
            }
            $liveAllow = isset($live[$name]) ? $this->sectionValues($live[$name], 'allow') : [];
            if ($liveAllow && (array_diff($trunkCodecs, $liveAllow) || array_diff($liveAllow, $trunkCodecs))) {
                $warnings[] = "Codec change: {$name} is currently ".implode(',', $liveAllow)." in live pjsip.conf and would become ".implode(',', $trunkCodecs);
            }

            if ($context === $inboundContext) {
                $limits[$name] = [
                    ((int) ($t->max_channels ?? 0)) > 0 ? (int) $t->max_channels : self::DEFAULT_MAX_CHANNELS,
                    ((int) ($t->max_call_duration ?? 0)) > 0 ? (int) $t->max_call_duration : self::DEFAULT_MAX_DURATION,
                ];
            }
            $endpoints[] = [
                'trunk_id' => $t->id ?? null,
                'supplier' => $label,
                'pjsip' => $name,
                'auth' => strtoupper($useAuth ? $authType : 'ip'),
                'context' => $context,
                'status' => 'ACTIVE',
                'ips' => $ips,
                'codecs' => $trunkCodecs,
                'max_channels' => $limits[$name][0] ?? null,
                'max_call_duration' => $limits[$name][1] ?? null,
            ];
        }

        // A protected route that is inactive/absent in the trunks table is
        // still preserved: deactivating it in the DB must not delete it from live.
        foreach (self::PROTECTED_ROUTES as $pname => $pctx) {
            if (in_array($pname, $names, true) || !isset($live[$pname])) {
                continue;
            }
            $names[] = $pname;
            $this->emitProtected($pname, null, $live, $out, $errors, $warnings, $endpoints, $identifyCount);
            $warnings[] = "{$pname} is protected: kept unchanged from live pjsip.conf although it is inactive/absent in the trunks table";
        }

        $out[] = self::PJSIP_END;

        return [
            'text' => implode("\n", $out)."\n",
            'names' => $names,
            'skipped' => $skipped,
            'warnings' => $warnings,
            'errors' => $errors,
            'endpoints' => $endpoints,
            'limits' => $limits,
            'identify_count' => $identifyCount,
        ];
    }

    /**
     * Re-emits a protected route's live sections byte-for-byte. If they cannot
     * be found (or are not on the protected context) Apply is blocked rather
     * than regenerating the route from the DB.
     */
    private function emitProtected(string $name, ?object $t, array $live, array &$out, array &$errors, array &$warnings, array &$endpoints, int &$identifyCount): void
    {
        $protectedContext = self::PROTECTED_ROUTES[$name];
        if (!isset($live[$name])) {
            $errors[] = self::PROTECTED_MESSAGE." ({$name}: section not found in live pjsip.conf managed block)";

            return;
        }
        $liveContext = $this->sectionValue($live[$name], 'context');
        if ($liveContext !== $protectedContext) {
            $errors[] = self::PROTECTED_MESSAGE." ({$name}: live context is \"{$liveContext}\", expected \"{$protectedContext}\")";

            return;
        }

        $out[] = "; ── {$name} (PROTECTED — preserved verbatim from live pjsip.conf) ──";
        foreach ([$name, "{$name}-aor", "{$name}-identify", "{$name}-auth"] as $sec) {
            if (isset($live[$sec])) {
                foreach ($live[$sec] as $line) {
                    $out[] = $line;
                }
                $out[] = '';
            }
        }
        $ips = isset($live["{$name}-identify"]) ? $this->sectionValues($live["{$name}-identify"], 'match') : [];
        if (isset($live["{$name}-identify"])) {
            $identifyCount++;
        }
        if ($t && trim((string) ($t->dialplan_context ?? '')) !== $protectedContext) {
            $warnings[] = "Protected supplier {$name}: trunks.dialplan_context is \"".($t->dialplan_context ?? '')."\" but the live protected route uses \"{$protectedContext}\" — the DB value is ignored";
        }
        $endpoints[] = [
            'trunk_id' => $t->id ?? null,
            'supplier' => $t ? ($t->nickname ?: $t->name) : $name,
            'pjsip' => $name,
            'auth' => 'IP',
            'context' => $protectedContext,
            'status' => 'PROTECTED',
            'ips' => $ips,
            'codecs' => $this->sectionValues($live[$name], 'allow'),
            'max_channels' => null,
            'max_call_duration' => null,
        ];
    }

    /** section name => its lines. A section ends at a blank line or a comment. */
    public function parseSections(string $text): array
    {
        $sections = [];
        $cur = null;
        foreach (preg_split('/\r?\n/', $text) as $line) {
            if (preg_match('/^\[([^\]]+)\]/', $line, $m)) {
                $cur = $m[1];
                $sections[$cur] = [$line];
                continue;
            }
            if ($cur === null) {
                continue;
            }
            if (trim($line) === '' || str_starts_with(ltrim($line), ';')) {
                $cur = null;
                continue;
            }
            $sections[$cur][] = $line;
        }

        return $sections;
    }

    private function sectionValues(array $lines, string $key): array
    {
        $vals = [];
        foreach ($lines as $l) {
            if (preg_match('/^\s*'.preg_quote($key, '/').'\s*=\s*(.*?)\s*$/', $l, $m)) {
                $vals[] = $m[1];
            }
        }

        return $vals;
    }

    private function sectionValue(array $lines, string $key): ?string
    {
        return $this->sectionValues($lines, $key)[0] ?? null;
    }

    /**
     * @param  iterable  $routePrefixes  rows from `route_prefixes`
     * @param  iterable  $ivrs  rows from `ivrs`
     * @param  array  $limits  pjsip name => [max_channels, max_call_duration] for endpoints on $inboundContext
     * @return array{text:string,routes:array,errors:string[],warnings:string[]}
     */
    /**
     * Default IVR: pick one IVR at random from the AstDB family ivr_pool (count + 1..N, kept in
     * sync by the API) on EVERY call. No MySQL/HTTP in the call path. An empty/missing pool, or
     * a picked context that is not loaded, falls back to the default IVR; with no usable IVR at
     * all the call is ended instead of jumping into a missing context.
     * IVR_CONTEXT is set to the final choice, so the CDR records the IVR actually played.
     */
    private function defaultIvrPoolLines(string $pattern, string $label): array
    {
        $fb = self::DEFAULT_IVR;

        return [
            "exten => {$pattern},1,NoOp({$label} -> default IVR pool)",
            " same => n,Set(IVR_CONTEXT={$fb})",
            ' same => n,GotoIf($[!${DB_EXISTS(ivr_pool/count)}]?go)',
            ' same => n,Set(POOL_N=${DB(ivr_pool/count)})',
            ' same => n,GotoIf($[0${POOL_N} < 1]?go)',
            ' same => n,Set(POOL_PICK=${DB(ivr_pool/${RAND(1,${POOL_N})})})',
            ' same => n,ExecIf($[${DIALPLAN_EXISTS(${POOL_PICK},s,1)}]?Set(IVR_CONTEXT=${POOL_PICK}))',
            ' same => n(go),NoOp(default IVR -> ${IVR_CONTEXT})',
            ' same => n,GotoIf($[${DIALPLAN_EXISTS(${IVR_CONTEXT},s,1)}]?${IVR_CONTEXT},s,1)',
            ' same => n,NoOp(no usable IVR for ${EXTEN})',
            ' same => n,Hangup()',
        ];
    }

    public function dialplanManagedBlock(iterable $routePrefixes, iterable $ivrs, string $inboundContext = self::NORMAL_CONTEXT, array $limits = []): array
    {
        $validation = $this->validatePrefixes($routePrefixes);

        if (in_array($inboundContext, self::RESERVED_CONTEXTS, true) || !preg_match('#^[A-Za-z0-9_\-/]+$#', $inboundContext)) {
            $validation['errors'][] = "Inbound context \"{$inboundContext}\" is reserved or invalid — it would collide with a hand-written context in extensions.conf";
        }

        $activeIvrNames = [];
        foreach ($ivrs as $ivr) {
            $ivr = (object) $ivr;
            if (!empty($ivr->is_active)) {
                $activeIvrNames["custom/{$ivr->name}"] = true;
            }
        }
        // A route into a missing/inactive IVR would Goto a context that does
        // not exist, so it blocks Apply and is never emitted.
        $routes = [];
        foreach ($validation['active'] as $row) {
            // the default IVR is the pool: resolved per call, so it needs no fixed context here
            if ($row->ivr_context !== self::DEFAULT_IVR && !isset($activeIvrNames[$row->ivr_context])) {
                $validation['errors'][] = "Route \"{$row->prefix}\" (#{$row->id}) references IVR context \"{$row->ivr_context}\" which is not an active IVR — Apply blocked (missing IVR)";
                continue;
            }
            $routes[] = $row;
        }
        // Most specific prefix first, so the emitted order is deterministic
        // (Asterisk also picks the most specific pattern regardless of order).
        usort($routes, function ($a, $b) {
            return (strlen($b->prefix) <=> strlen($a->prefix))
                ?: (($a->priority ?? 1) <=> ($b->priority ?? 1))
                ?: ($a->id <=> $b->id);
        });

        $out = [self::DIALPLAN_BEGIN, ''];

        $out[] = "[{$inboundContext}]";
        $out[] = '';
        $out[] = 'exten => _X.,1,NoOp(6G PREMIUM TELECOM INBOUND)';
        $out[] = ' same => n,NoOp(Caller=${CALLERID(num)})';
        $out[] = ' same => n,NoOp(DID=${EXTEN})';
        $out[] = ' same => n,Set(CALL_START=${EPOCH})';
        $out[] = ' same => n,Set(DID_NUMBER=${EXTEN})';
        // Numbers disabled in the panel are flagged in the local Asterisk AstDB
        // (family blocked_dids) - a memory lookup, still no MySQL/HTTP at call time.
        $out[] = ' same => n,GotoIf($[${DB_EXISTS(blocked_dids/${EXTEN})}]?blocked)';
        $out[] = ' same => n,Set(SUPPLIER=${CHANNEL(endpoint)})';
        $out[] = ' same => n,Gosub(supplier-limits,${SUPPLIER},1)';
        $out[] = ' same => n,Set(GROUP(supplier)=${SUPPLIER})';
        $out[] = ' same => n,GotoIf($[${GROUP_COUNT(${SUPPLIER}@supplier)} > ${SUP_MAXCH}]?limit)';
        $out[] = ' same => n,Set(TIMEOUT(absolute)=${SUP_MAXDUR})';
        $out[] = ' same => n,Goto(number-routing,${EXTEN},1)';
        $out[] = ' same => n(limit),NoOp(CONCURRENT LIMIT ${SUP_MAXCH} reached for ${SUPPLIER})';
        $out[] = ' same => n,Hangup(34)';
        $out[] = ' same => n(blocked),NoOp(DISABLED DID ${EXTEN})';
        $out[] = ' same => n,Hangup(21)';
        $out[] = '; E.164 / 00 international forms are normalised to bare digits, like [from-carrier]';
        $out[] = "exten => _+X.,1,Goto({$inboundContext},\${EXTEN:1},1)";
        $out[] = "exten => _00X.,1,Goto({$inboundContext},\${EXTEN:2},1)";
        $out[] = '';

        // Per-supplier limits are baked in as static dialplan (no DB at call time).
        $out[] = '[supplier-limits]';
        $out[] = '';
        foreach ($limits as $pjsipName => [$maxCh, $maxDur]) {
            $out[] = "exten => {$pjsipName},1,Set(SUP_MAXCH={$maxCh})";
            $out[] = " same => n,Set(SUP_MAXDUR={$maxDur})";
            $out[] = ' same => n,Return()';
        }
        // fallback for an endpoint with no explicit entry (pjsip names start with a letter/digit)
        $out[] = 'exten => _[0-9A-Za-z].,1,Set(SUP_MAXCH='.self::DEFAULT_MAX_CHANNELS.')';
        $out[] = ' same => n,Set(SUP_MAXDUR='.self::DEFAULT_MAX_DURATION.')';
        $out[] = ' same => n,Return()';
        $out[] = '';

        $out[] = '[number-routing]';
        $out[] = '';
        foreach ($routes as $row) {
            $pattern = $this->toDialplanPattern($row->prefix);
            $label = ($row->country_name ?? null) ?: ($row->country_code ?? null) ?: 'Route';
            if ($row->ivr_context === self::DEFAULT_IVR) {
                array_push($out, ...$this->defaultIvrPoolLines($pattern, $label));
                continue;
            }
            $out[] = "exten => {$pattern},1,NoOp({$label} -> {$row->ivr_context})";
            $out[] = " same => n,Set(IVR_CONTEXT={$row->ivr_context})";
            $out[] = " same => n,Goto({$row->ivr_context},s,1)";
        }
        $out[] = '';
        $out[] = '; Unknown/unconfigured DID — never enters an IVR';
        $out[] = 'exten => _X.,1,NoOp(UNKNOWN DID ${EXTEN})';
        $out[] = ' same => n,Hangup()';
        $out[] = '';

        foreach ($ivrs as $ivr) {
            $ivr = (object) $ivr;
            if (empty($ivr->is_active)) {
                continue;
            }
            $out[] = "[custom/{$ivr->name}]";
            $out[] = '';
            $out[] = 'exten => s,1,Answer()';
            $out[] = " same => n,Playback(custom/{$ivr->name})";
            $out[] = ' same => n,WaitExten(10)';
            // CDR for the generated path (same AGI as [from-carrier]); the DID
            // is passed explicitly because CDR(dst) is "s" after the Goto.
            $out[] = 'exten => h,1,NoOp(CDR SAVE START - billsec=${CDR(billsec)})';
            $out[] = ' same => n,AGI(save_cdr.php,${CDR(src)},${DID_NUMBER},${CDR(billsec)},${TARIFF},${IVR_CONTEXT},${CHANNEL})';
            $out[] = ' same => n,System(/usr/local/bin/import_cdr.sh >> /tmp/cdr_import.log 2>&1 &)';
            $out[] = '';
        }

        $out[] = self::DIALPLAN_END;

        return [
            'text' => implode("\n", $out)."\n",
            'routes' => $routes,
            'errors' => $validation['errors'],
            'warnings' => $validation['warnings'],
        ];
    }

    public function rtpConf(int $start, int $end): string
    {
        return implode("\n", [
            '[general]',
            "rtpstart={$start}",
            "rtpend={$end}",
            '',
        ]);
    }

    /**
     * Blocking errors: exact-duplicate active prefixes (ambiguous — Asterisk
     * cannot have two identical extension patterns in the same context).
     * Warnings: one active prefix is a strict textual prefix of another,
     * which is legal (Asterisk picks the most specific match) but worth a
     * human glance before Apply.
     */
    public function validatePrefixes(iterable $routePrefixes): array
    {
        $active = [];
        foreach ($routePrefixes as $row) {
            $row = (object) $row;
            if (!empty($row->is_active)) {
                $active[] = $row;
            }
        }
        usort($active, fn ($a, $b) => ($a->priority ?? 1) <=> ($b->priority ?? 1));

        $errors = [];
        $warnings = [];
        $seen = [];
        foreach ($active as $row) {
            $key = (string) $row->prefix;
            if (isset($seen[$key])) {
                $errors[] = "Duplicate active prefix \"{$key}\" (rows #{$seen[$key]} and #{$row->id}) — ambiguous routing";
            }
            $seen[$key] = $row->id;
        }
        foreach ($active as $a) {
            foreach ($active as $b) {
                if ($a->id === $b->id) {
                    continue;
                }
                if (strlen($a->prefix) < strlen($b->prefix) && str_starts_with((string) $b->prefix, (string) $a->prefix)) {
                    $warnings[] = "Prefix \"{$a->prefix}\" (#{$a->id}) overlaps with more specific \"{$b->prefix}\" (#{$b->id})";
                }
            }
        }

        return ['active' => $active, 'errors' => $errors, 'warnings' => $warnings];
    }

    public function validateRtp(int $start, int $end): array
    {
        $errors = [];
        if ($start < 1 || $start > 65535) {
            $errors[] = 'RTP start port must be between 1 and 65535';
        }
        if ($end < 1 || $end > 65535) {
            $errors[] = 'RTP end port must be between 1 and 65535';
        }
        if ($start >= $end) {
            $errors[] = 'RTP start port must be less than RTP end port';
        }

        return $errors;
    }

    /**
     * A prefix that already contains Asterisk pattern syntax (X/Z/N/.) is
     * used verbatim; a plain digit string is treated as "starts with these
     * digits" via the standard `_<digits>.` convention.
     */
    private function toDialplanPattern(string $prefix): string
    {
        $prefix = trim($prefix);
        if ($prefix === '') {
            return '_X.';
        }
        if (preg_match('/[XZN.\[\]]/', $prefix)) {
            return str_starts_with($prefix, '_') ? $prefix : "_{$prefix}";
        }

        return "_{$prefix}.";
    }

    private function cleanCodecs(string $csv): array
    {
        $codecs = array_values(array_unique(array_filter(
            array_map('trim', explode(',', $csv)),
            fn ($c) => in_array($c, self::INSTALLED_CODECS, true)
        )));

        return $codecs ?: ['ulaw', 'alaw'];
    }
}
